version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: nextjs_postgres
    restart: always
    ports:
      - "6500:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
